# Generated by Django 2.0 on 2017-12-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_team_tri_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='team',
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
