# Generated by Django 2.0 on 2017-12-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_auto_20171223_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
    ]
