# Generated by Django 2.0 on 2017-12-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0006_auto_20171226_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
