# Generated by Django 2.0 on 2017-12-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0008_auto_20171228_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(default='0.0', max_length=10)),
                ('rebounds', models.CharField(default='0.0', max_length=10)),
                ('assists', models.CharField(default='0.0', max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.Player')),
            ],
        ),
    ]
