# Generated by Django 2.0 on 2017-12-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0009_playerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
