# Generated by Django 2.0 on 2017-12-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0010_auto_20171229_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nba.Team'),
        ),
    ]
