# Generated by Django 2.0 on 2017-12-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0011_playerstats_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.CharField(default='0.0', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.CharField(default='0.0', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='rebounds',
            field=models.CharField(default='0.0', max_length=10),
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
