# Generated by Django 2.0 on 2017-12-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0013_auto_20171229_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.CharField(default='0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.CharField(default='0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='rebounds',
            field=models.CharField(default='0.0', max_length=10),
        ),
    ]
