# Generated by Django 2.0 on 2018-01-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0016_auto_20180101_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
