# Generated by Django 2.0 on 2018-01-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0017_auto_20180101_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/logos'),
        ),
    ]
