# Generated by Django 2.0 on 2018-01-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0018_auto_20180102_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dob',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.CharField(default='', max_length=6),
        ),
    ]
