# Generated by Django 2.0 on 2018-01-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0019_auto_20180103_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='college',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='draft',
            field=models.CharField(default='', max_length=200),
        ),
    ]
