# Generated by Django 2.0 on 2018-01-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0020_auto_20180103_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(null=True, upload_to='static/player_pics'),
        ),
        migrations.AddField(
            model_name='player',
            name='url',
            field=models.CharField(default='', max_length=400),
        ),
    ]
