# Generated by Django 2.0 on 2018-01-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0022_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='isHomeTeam',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='opponentScore',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='score',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='team',
        ),
    ]
