# Generated by Django 2.0 on 2018-01-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0025_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='opponentScore',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
