# Generated by Django 2.0 on 2018-01-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0026_auto_20180108_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='opponentScore',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
