# Generated by Django 2.0 on 2018-01-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0028_schedule_gameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='gameId',
            field=models.IntegerField(),
        ),
    ]
