# Generated by Django 2.0 on 2018-01-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0029_auto_20180108_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='gameId',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
